version: "3.8"
services:
  mongdb-class-ingresso:
    image: mongo:latest
    container_name: mongodb-class-ingresso
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - mongo-network

volumes:
  mongo-data:

networks:
  mongo-network:
